on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: abystoma/hello-world-composite-action@v6
        with:
          who-to-greet: 'this is a message running in my first action'
